### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by MuradAbbaszade** [rfch-world/social-media#5]
### Outh2,Email verification,Register and others

**Login system will be written**

![image](https://user-images.githubusercontent.com/98694275/214268907-8ea25e8b-6331-4b66-93f2-7b7610aac0c2.png)

**Registration system will be written**

![image](https://user-images.githubusercontent.com/98694275/214269035-156e0fd6-cc5d-4a0f-81e4-b9b75530c58f.png)

**Email verification** 

![image](https://user-images.githubusercontent.com/98694275/214268831-759d14dd-22f1-474a-91ab-a1453efaa9ed.png)

**Comment by vugarbakhishli** [comment]
can you assign the task to me properly?

**Comment by MuradAbbaszade** [comment]
User registration and login added
